<a href="https://colab.research.google.com/github/carmenortegal/matem-ticasfinancierasII/blob/main/Pr%C3%A1ctica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Cálculo de la TIR y el precio de un bono**


In [5]:
pip install numpy-financial #se instala la librería que nos permitirá hacer diferentes cálculos financieros

In [6]:
pip install numpy

In [87]:
import numpy_financial as npf #se asigna un alias a la librería instalada
import numpy as np

#Se introducen los flujos de cada bono
cfA = [-96, 100,0,0,0,0]
cfB=[-545,50,550,0,0,0]
cfC=[-1030,70,70,1070,0,0]
cfD=[-2030,150,150,150,2150,0]
cfE=[-3920,300,300,300,300,4300]
cfX=[0,100,100,100,100,1100]

CF=np.concatenate(([cfA],[cfB],[cfC],[cfD],[cfE]))

print(CF)


[[  -96   100     0     0     0     0]
 [ -545    50   550     0     0     0]
 [-1030    70    70  1070     0     0]
 [-2030   150   150   150  2150     0]
 [-3920   300   300   300   300  4300]]


In [10]:
#Cálculo de la TIR de los bonos A-E con una función específica de la librería instalada (irr)
tirA = npf.irr(cfA)
tirB = npf.irr(cfB)
tirC = npf.irr(cfC)
tirD = npf.irr(cfD)
tirE = npf.irr(cfE)

print(f"TIR BONO A: {tirA:.2%}")
print(f"TIR BONO B: {tirB:.2%}")
print(f"TIR BONO C: {tirC:.2%}")
print(f"TIR BONO D: {tirD:.2%}")
print(f"TIR BONO E: {tirE:.2%}")

TIR BONO A: 4.17%
TIR BONO B: 5.15%
TIR BONO C: 5.88%
TIR BONO D: 7.06%
TIR BONO E: 8.00%


In [61]:
#Cálculo de la ETTI
etti_calculada = [tirA,0,0,0,0]  #Sabemos que la ETTI del primer año se corresponde con la del Bono A ya que es un bono cupón cero
def calcula_etti(cf, etti_calculada): #se define una función que calculará la ETTI para el resto de periodos
    n = [i for i, e in enumerate(cf) if e != 0][-1]
    ultimo_flujo = cf[n]
    precio = -cf[0]
    fcid = 0 
    for t in range(1,n):
        fcid += cf[t] / (1+etti_calculada[t-1])**t
    return (ultimo_flujo / (precio - fcid))**(1/n)-1

etti_calculada[1] = calcula_etti(cfB, etti_calculada) # calculamos ETTI en n=2 conocido el bono B y ETTI del año 1

etti_calculada[2] = calcula_etti(cfC, etti_calculada) # calculamos ETTI en n=3 conocido el bono C y ETTI de los años 1 y 2

etti_calculada[3] = calcula_etti(cfD, etti_calculada) # calculamos ETTI en n=4 conocidos los bonos D y ETTI de los años 1, 2 y 3

etti_calculada[4] = calcula_etti(cfE, etti_calculada) # calculamos ETTI en n=5 conocido el bono E y ETTI de los años 1, 2, 3 y 4


for i in range(len(etti_calculada)):
    print(f"La ETTI del año {i+1} es {etti_calculada[i]:.2%}")

La ETTI del año 1 es 4.17%
La ETTI del año 2 es 5.20%
La ETTI del año 3 es 5.95%
La ETTI del año 4 es 7.26%
La ETTI del año 5 es 8.33%


In [86]:
#Cálculo del precio del bono X
def calcula_precio(cf,ti): #Se define una función que calcule el precio del bono X dados unos flujos (del bono X) y unos tipos de interés (ETTI)
  precio = 0
  for i in range(1,len(cf)):
    precio += cf[i] * (1+ti[i-1])**-i
  return precio   


precioX= calcula_precio(cfX, etti_calculada)
print(f"el precio del Bono X es: {precioX:,.2f}€")

cfX[0]=-precioX
print(f"los flujos del Bono X son: {cfX}")

#Cálculo de la TIR del bono X mediante la función irr de numpy_financial
tirX=npf.irr(cfX)
print(f"La TIR del Bono X es: {tirX:.2%}")



el precio del Bono X es: 1,083.25€
los flujos de caja del Bono X son: [-1083.2522022742555, 100, 100, 100, 100, 1100]
La TIR del Bono X es: 7.92%
